### ISSUE TITLE
Please add opengl 3.3 support

### ISSUE THREAD

**Issue by dimutch833** [TheCherno/OpenGL#3]

**Comment by SeppahBaws** [comment]
But why though? I don't see the point in supporting OpenGL versions all the way back to 3.3, since a lot of useful new stuff has been added since 4.0.
One instance of such a feature is `glDebugMessageCallback` which is the base thing the entire OpenGLDebug depends on.

**Comment by dimutch833** [comment]
i don need it glDebugMessageCallback
